// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/logout.ts";
import * as $3 from "./routes/api/ws.ts";
import * as $4 from "./routes/chat.tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Gooi.tsx";
import * as $$1 from "./islands/MessageList.tsx";
import * as $$2 from "./islands/UserStatus.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/logout.ts": $2,
    "./routes/api/ws.ts": $3,
    "./routes/chat.tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Gooi.tsx": $$0,
    "./islands/MessageList.tsx": $$1,
    "./islands/UserStatus.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
